update: Finalise test simulation for MacOS
jonas-rem/flownexus pull request #71
Opened 2024-08-28 16:27 UTC by Kappuccino111

This commit finalises the simulation for MacOS. Humidity values have also been added to the simulation.

2024-08-28 16:30 UTC, Kappuccino111 commented
@jonas-rem, this should now be compatible with the entire UNIX system. No guarantees on Windows, though—it's unpredictable! 😂

2024-08-29 08:05 UTC, jonas-rem requested changes
Looks good to me and works under Linux. Check my comments, maybe we can clean it up a little, then we're ready to go.

2024-08-29 08:05 UTC, jonas-rem commented on server/django/sensordata/templates/graph_dashboard.html
> +    <option value="humidity">Humidity</option>
I guess this is unrelated to the fix?

2024-08-29 08:05 UTC, jonas-rem commented on simulation/Dockerfile
> -RUN apt-get install -y libc6:i386 libstdc++6:i386 libc6-i386
Since we are using the 64 bit native client we could completely remove the i386 libs, as well as `RUN dpkg --add-architecture i386`.

2024-08-30 10:00 UTC, Kappuccino111 commented on server/django/sensordata/templates/graph_dashboard.html
> +    <option value="humidity">Humidity</option>
Updated in the latest commit. Pushing to a later PR.

2024-08-30 10:02 UTC, Kappuccino111 commented on simulation/Dockerfile
> -RUN apt-get install -y libc6:i386 libstdc++6:i386 libc6-i386
Updated in https://github.com/jonas-rem/flownexus/pull/71/commits/2193f22d80bd2a9b796afff951af8d6da1b23510

2024-08-30 10:02 UTC, jonas-rem approved these changes

2024-08-30 10:02 UTC, Kappuccino111 commented
@jonas-rem should be ready for merge now 👍

2024-08-30 10:14 UTC, merged